data:
  voc_dir: 'VOCdevkit/VOC2007'
  val_ratio: 0.2
  batch_size: 8

model:
  pretrained_dir: 'ssd_resnet50_v1_fpn_640x640_coco17_tpu-8'
  num_classes: 20
  max_detections_per_class: 100
  max_total_detections: 100
  
train:
  n_epochs: 10
  learning_rate: 0.001

seed: 42

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%dT%H-%M-%S}  
