version: '3.8'
services:
  preprocess:
    build:
      context: ./components/preprocess
      dockerfile: Dockerfile
    image: gcr.io/${GCP_PROJECT_ID}/vp-sample-preprocess:latest
  train:
    build:
      context: ./components/train
      dockerfile: Dockerfile
    image: gcr.io/${GCP_PROJECT_ID}/vp-sample-train:latest
  evaluate:
    build:
      context: ./components/evaluate
      dockerfile: Dockerfile
    image: gcr.io/${GCP_PROJECT_ID}/vp-sample-evaluate:latest
  deploy:
    build:
      context: ./components/deploy
      dockerfile: Dockerfile
    image: gcr.io/${GCP_PROJECT_ID}/vp-sample-deploy:latest
  serving:
    build:
      context: ./docker/serving
      dockerfile: Dockerfile
    image: gcr.io/${GCP_PROJECT_ID}/vp-sample-serving:latest
