version: '3.8'
services:
  app:
    build:
      context: ./streamlit-front
      dockerfile: Dockerfile
    image: st-fastapi-example/app:latest
    container_name: app
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - st_fastapi_net
    environment:
      BACKEND_HOST: backend:80
    ports:
      - 8080:8080

  backend:
    build:
      context: ./fastapi-backend
      dockerfile: Dockerfile
    image: st-fastapi-example/backend:latest
    container_name: backend
    restart: unless-stopped
    networks:
      - st_fastapi_net
    ports:
      - 80:80
    environment:
      BUCKET_NAME: streamlit-fastapi-example
      GOOGLE_APPLICATION_CREDENTIALS: gcs-credentials.json
      APP_MODULE: server:app

networks:
  st_fastapi_net:
    driver: bridge
  
    
      
